apiVersion: v1
kind: ServiceAccount
metadata:
  name: wispy-server-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::990317434218:role/wispy-server-s3-access-role"
---
apiVersion: v1
kind: Secret
metadata:
  name: wispy-server-sa-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: wispy-server-sa
type: kubernetes.io/service-account-token